### PR TITLE
Add support for sending HTTP 405 - Method Not Allowed.

### PR DESCRIPTION
**Pull request by dmortondev**
Add support for HTTP 405 responses when a requested
resource exists, but does not support the requested method.

Also add additional unit tests to cover the change.

---
This change is [Reviewable](https://reviewable.io/reviews/spirentorion/pistache/2)

### CODE REVIEW

**Review by djoyner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirentorion/pistache/2)* status: all files reviewed, 3 unresolved discussions (waiting on @dmorton-spirent)

___
*[src/server/router.cc, line 446 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWEJMO75el6FYAuS8S9:-LWEJMO75el6FYAuS8SA:b-kbyjxj) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/src/server/router.cc#L446)):*
> ```cpp
>     //No route or custom handler found. Let's walk through the list of other methods and see if any of them support
>     // this resource. This will allow server to send a HTTP 405 (method not allowed) response.
>     //RFC requires HTTP 405 responses to include a list of supported methods for the requested resource.
> ```

Minor:  Pls cleanup comment formatting.
___
*[src/server/router.cc, line 448 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWEJaRb4tqAVcmrnEi-:-LWEJaRb4tqAVcmrnEi0:b-sjo8x1) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/src/server/router.cc#L448)):*
> ```cpp
>     //RFC requires HTTP 405 responses to include a list of supported methods for the requested resource.
>     std::vector<Http::Method> supportedMethods;
>     for (auto& methods: routes) {
> ```

This is `O(N)` in the number of routes that the router knows?
___
*[src/server/router.cc, line 466 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWEJDYM64w-T61eeErV:-LWEJDYM64w-T61eeErW:b-jntfxl) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/src/server/router.cc#L466)):*
> ```cpp
>         invokeNotFoundHandler(req, std::move(response));
>     } else {
>         response.send(Http::Code::Not_Found, "Could not find a matching route");
> ```

Minor: Watch out for unnecessary whitespace changes (upstream maintainer may reject our PR due to what amounts to editor misconfig vs what they expect).

**Review by DerangedMonkeyNinja — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirentorion/pistache/2)* status: all files reviewed, 5 unresolved discussions (waiting on @dmorton-spirent and @djoyner)

___
*[include/pistache/http.h, line 492 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWGak6N7wJg_G_cJFTE:-LWGak6N7wJg_G_cJFTF:bnnp2wv) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/include/pistache/http.h#L492)):*
> ```objc
>     Async::Promise<ssize_t> sendMethodNotAllowed(const std::vector<Http::Method>& supportedMethods) {
>         code_ = Http::Code::Method_Not_Allowed;
>         headers_.add(std::shared_ptr<Http::Header::Header>(new Header::Allow(supportedMethods)));
> ```

C++ nit: I think "std::make_shared" is always preferred over using "new" directly.
___
*[include/pistache/http.h, line 493 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWGcz-7DJL1njHFS3xu:-LWGcz-7DJL1njHFS3xv:b-60y1rm) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/include/pistache/http.h#L493)):*
> ```objc
>         code_ = Http::Code::Method_Not_Allowed;
>         headers_.add(std::shared_ptr<Http::Header::Header>(new Header::Allow(supportedMethods)));
>         std::string body = "Method Not Allowed";
> ```

You should be able to get this value using 'const char* codeString(Code)' function without having to redefine it.
___
*[src/server/router.cc, line 448 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWEJaRb4tqAVcmrnEi-:-LWGdyfC1DlY4cJgXJFU:b-ca2p2l) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/src/server/router.cc#L448)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

This is `O(N)` in the number of routes that the router knows?
</blockquote></details>

Yep.  Looks like 'routes' is a method -> vector<Route> hashtable.  Seems... like a poor choice by Pistache.

**Review by djoyner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirentorion/pistache/2)* status: all files reviewed, 4 unresolved discussions (waiting on @dmorton-spirent)

**Review by dmortondev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirentorion/pistache/2)* status: all files reviewed, 4 unresolved discussions (waiting on @dmorton-spirent and @DerangedMonkeyNinja)

___
*[include/pistache/http.h, line 492 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWGak6N7wJg_G_cJFTE:-LWHqY5s3A44nCwrD2KS:b-ibwia1) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/include/pistache/http.h#L492)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

C++ nit: I think "std::make_shared" is always preferred over using "new" directly.
</blockquote></details>

I was wondering what that did... Will switch over. Thanks for the tip!
___
*[include/pistache/http.h, line 493 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWGcz-7DJL1njHFS3xu:-LWHqjBy1jY9vZHUSdGh:buws9ca) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/include/pistache/http.h#L493)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

You should be able to get this value using 'const char* codeString(Code)' function without having to redefine it.
</blockquote></details>

Oh right, missed that one.
___
*[src/server/router.cc, line 446 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWEJMO75el6FYAuS8S9:-LWHqpGpEOV-fs9PSydc:bhy9ot6) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/src/server/router.cc#L446)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

Minor:  Pls cleanup comment formatting.
</blockquote></details>

Will do.
___
*[src/server/router.cc, line 448 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWEJaRb4tqAVcmrnEi-:-LWHpsy17pj4J-puuY-Y:b-bx9f66) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/src/server/router.cc#L448)):*
<details><summary><i>Previously, DerangedMonkeyNinja (Timmons C. Player) wrote…</i></summary><blockquote>

Yep.  Looks like 'routes' is a method -> vector<Route> hashtable.  Seems... like a poor choice by Pistache.
</blockquote></details>

Sadly, yeah it's probably pretty close to O(n). I think they did do a refactor and switch to a tree structure from a straight linear match in the previous revision we had.

This is the part I was concerned about when I mentioned performance while discussing the implementation earlier.
___
*[src/server/router.cc, line 466 at r1](https://reviewable.io/reviews/spirentorion/pistache/2#-LWEJDYM64w-T61eeErV:-LWHqsI4-Nc0qCPMfQJk:bhy9ot6) ([raw file](https://github.com/spirentorion/pistache/blob/5e3386573852d04a7377eb89b4ade4ac191575a7/src/server/router.cc#L466)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

Minor: Watch out for unnecessary whitespace changes (upstream maintainer may reject our PR due to what amounts to editor misconfig vs what they expect).
</blockquote></details>

Will do.

**Review by DerangedMonkeyNinja — APPROVED** [review]

**Pull request merged**
